"""initial_schema

Revision ID: 31a4862b13f5
Revises: 
Create Date: 2026-02-09 21:58:09.019319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a4862b13f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_categories',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('name_th', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('order_num', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_th')
    )
    op.create_table('content_goals',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('name_th', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('prompt_hint', sa.String(length=500), nullable=True),
    sa.Column('order_num', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_th')
    )
    op.create_table('drafts',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('draft_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drafts_session_id'), ['session_id'], unique=False)

    op.create_table('style_profiles',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('target_audiences',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('name_th', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('age_range', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('order_num', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_th')
    )
    op.create_table('video_profiles',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name_th', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('description_th', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('order_num', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visual_tags',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visual_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visual_tags_category'), ['category'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('default_style', sa.String(length=50), nullable=True),
    sa.Column('video_profile_id', sa.String(length=50), nullable=True),
    sa.Column('target_duration', sa.Integer(), nullable=True),
    sa.Column('character_reference', sa.Text(), nullable=True),
    sa.Column('full_script', sa.Text(), nullable=True),
    sa.Column('style_instructions', sa.Text(), nullable=True),
    sa.Column('script_text', sa.Text(), nullable=True),
    sa.Column('audio_path', sa.String(length=255), nullable=True),
    sa.Column('audio_duration', sa.Float(), nullable=True),
    sa.Column('drive_folder_link', sa.String(length=500), nullable=True),
    sa.Column('aspect_ratio', sa.String(length=20), nullable=True),
    sa.Column('content_goal', sa.String(length=255), nullable=True),
    sa.Column('content_category', sa.String(length=100), nullable=True),
    sa.Column('target_audience', sa.String(length=255), nullable=True),
    sa.Column('content_description', sa.Text(), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=True),
    sa.Column('video_format', sa.String(length=50), nullable=True),
    sa.Column('voice_personality', sa.String(length=100), nullable=True),
    sa.Column('workflow_step', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_date', sa.DateTime(), nullable=True),
    sa.Column('video_type', sa.String(length=50), nullable=True),
    sa.Column('visual_theme', sa.String(length=255), nullable=True),
    sa.Column('directors_note', sa.Text(), nullable=True),
    sa.Column('direction_style', sa.String(length=100), nullable=True),
    sa.Column('direction_custom_notes', sa.Text(), nullable=True),
    sa.Column('upload_folder', sa.String(length=255), nullable=True),
    sa.Column('uploaded_files', sa.JSON(), nullable=True),
    sa.Column('final_video_path', sa.String(length=500), nullable=True),
    sa.Column('generated_content', sa.Text(), nullable=True),
    sa.Column('proposal_data', sa.JSON(), nullable=True),
    sa.Column('prompt_style_config', sa.JSON(), nullable=True),
    sa.Column('content_category_id', sa.CHAR(36), nullable=True),
    sa.Column('target_audience_id', sa.CHAR(36), nullable=True),
    sa.Column('content_goal_id', sa.CHAR(36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_category_id'], ['content_categories.id'], ),
    sa.ForeignKeyConstraint(['content_goal_id'], ['content_goals.id'], ),
    sa.ForeignKeyConstraint(['target_audience_id'], ['target_audiences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_segments',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('project_id', sa.CHAR(36), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_assets',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('project_id', sa.CHAR(36), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('asset_type', sa.String(length=50), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenes',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('project_id', sa.CHAR(36), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.Column('narration_text', sa.Text(), nullable=True),
    sa.Column('veo_prompt', sa.Text(), nullable=True),
    sa.Column('emotion', sa.String(length=50), nullable=True),
    sa.Column('visual_style', sa.String(length=50), nullable=True),
    sa.Column('subject_description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('estimated_duration', sa.Float(), nullable=True),
    sa.Column('video_generated', sa.Boolean(), nullable=True),
    sa.Column('audio_synced', sa.Boolean(), nullable=True),
    sa.Column('stock_video_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_logs',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('project_id', sa.CHAR(36), nullable=True),
    sa.Column('service_name', sa.String(length=50), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_logs')
    op.drop_table('scenes')
    op.drop_table('media_assets')
    op.drop_table('audio_segments')
    op.drop_table('projects')
    with op.batch_alter_table('visual_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visual_tags_category'))

    op.drop_table('visual_tags')
    op.drop_table('video_profiles')
    op.drop_table('target_audiences')
    op.drop_table('style_profiles')
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drafts_session_id'))

    op.drop_table('drafts')
    op.drop_table('content_goals')
    op.drop_table('content_categories')
    # ### end Alembic commands ###
